# General Policies {#sec-general-policy}

This section outlines the operational policies and practical guidelines that support our day-to-day work in PRIDE.

## Communication {#sec-communication}

The lab uses multiple platforms for different types of communication, and choosing the appropriate channel helps ensure messages are seen and addressed in a timely manner. Email is usually the preferred for method of communication to team members in most cases. This may include detailed information that requires documentation, or messages involving people outside the lab. For complex discussions, brainstorming, or matters requiring nuanced conversation, we encourage in-person or video meetings rather than lengthy email. For time-sensitive requests or important messages, we ask the lab members that lab members respond within 24 hours.

## Working Hours {#sec-work-hour}

PRIDE trusts that all members of our team can manage their time and work, recognizing that people have different working styles, peak productivity hours, and personal commitments. We prioritize outputs and impact over hours worked, and we support remote work and flexible schedules when feasible.

## Time Off and Sick Time

### Time Off (Vacation, PTO, and Floating Holiday) Requests {#sec-time-off}

PRIDE views time off (vacation, PTO, and floating holiday time) as part of staff’s holistic compensation package, and strongly encourages the use of accrued leave time for well-being and work-life balance. As such, PRIDE’s general philosophy towards requests for using accrued time off is “how can we get to a yes.” This is with the understanding that if there are conflicts, sometimes a “yes” may require adjusting the amount of time taken off or when it is taken.

Time off requests are assessed with the following criteria:

1.  any conflicting project deadlines;
2.  availability for work coverage during the time off;
3.  the employee has enough time accrued.

Time off requests are reviewed in the order they are received. If multiple staff request time off for the same day(s) that would cause a conflict with work coverage, then priority will be provided to the request made first. Longer periods of time off may require the supervisor to first check in with other staff who may be affected.

Any time off must be [requested in advance in writing]{.underline} by the employee, which is then assessed for [approval or modifications]{.underline} by the supervisor (see @sec-checklist for instructions on submitting written requests). Employees are encouraged to [not]{.underline} secure any time off plans (*e.g.*, purchasing airfare or hotels) until [after]{.underline} their time off request is formally approved.

Below are guidelines for advance notice that employees should provide for their time off requests, and how long to anticipate for the supervisor’s response. Submitting requests within these timeframes does not guarantee approval, but it helps to set the requests up to more easily get to a “yes.”

| Amount of Time Off Being Requested by Employee | Amount of Advance Notice Employee Provides | Amount of Time for Supervisor's Reply |
|--------------------------|-------------------------|---------------------|
| 1-2 days off | 5+ business days advance notice | 3 business days for reply |
| 3-5 days off | 10+ business days advance notice | 5 business days for reply |
| 6+ days off | 20+ business days advance notice | 10 business days for reply |

PRIDE understands that at times unforeseen situations may arise that make certain requests difficult to adhere to the above guidelines. Employees may still submit requests outside of the above guidelines, with the understanding they may be less likely to be approved if they conflict with work commitments and/or coverage available. PRIDE also understands that emergency situations may arise without advance notice, in which case employees are encouraged to consult with their supervisor directly.

Please read full details about vacation, PTO, and floating holiday accruals and institution-wide policies at [Stanford](https://adminguide.stanford.edu/chapters/human-resources/staff-employment-policies/vacations).

### Flex Time and Schedule Adjustment Requests {#sec-flex-time}

PRIDE’s work sometimes includes required events, conferences, and/or formal activities over the weekend. In these cases, flex time or schedule adjustments should be utilized.

[Non-exempt employees]{.underline} will request in writing a [schedule adjustment]{.underline} for the weekday(s) prior to the weekend worked, unless overtime is pre-approved by the supervisor. Overtime is defined as working more than 8 hours in one day or more than 40 hours in one week (for only the purpose of calculating overtime, Stanford’s work week is Monday through Sunday). At times a supervisor may assign a schedule adjustment to a non-exempt employee based on required weekend work assignments, in which case best efforts will be used to provide the employee with at least 10 business days advance notice.

-   An employee’s schedule adjustment request should mirror the number of hours worked on the weekend. For example, if someone works 4 hours at an event on a Saturday, then the schedule adjustment request should be 4 hours of not working on a Monday through Friday of the week preceding that Saturday worked.

[Exempt employees]{.underline} will request in writing flex time, which should be requested within 10 business days of the weekend work (the flex time does not need to be used within 10 business days, but the request needs to be submitted by then).

-   Flex time requests should mirror the amount of time worked on the weekend in increments of a half-day (for working between 1-4 hours) or a full day (for working between 5-8 hours).
-   Flex time for exempt employees is limited to weekend work for events, conferences, or formal activities (*e.g.*, facilitating a community listening session). If exempt staff elect to spend time on the weekend for their day-to-day work, this is excluded from flex time unless it is a special circumstance that is discussed and pre-approved by the supervisor.

See @sec-checklist Documentation Process Checklist for instructions on submitting written requests.

### Sick Time Notification / Requests {#sec-sick-time}

Sick time is most frequently not requested with advance notice, as employees can’t predict when they will get sick. Some sick time is possible with advance notice, for example medical procedures or medical appointments. See @sec-checklist below for the appropriate processes for employees to notify their supervisors of sick time with advance notice and sick time without advance notice.

Please read full details about sick time accruals, eligible situations to use sick time, and institution-wide policies at [Stanford](https://adminguide.stanford.edu/chapters/human-resources/staff-employment-policies/sick-time-regular-staff-employees-regular).

### Documentation Process Checklist {#sec-checklist}

[Time Off, Flex Time, Schedule Adjustments, and Sick Time with Advance Notice]{.underline}

1.  Employee submits the request on their individual Asana project “<<initial’s>> Time Off Requests & Sick Leave.” See sample [Asana project](https://app.asana.com/0/1207225117895958/1207225035274879) for the proper details.

2.  If approved by the supervisor:

    a.  Employee adds the time off to the PRIDE team calendar
    b.  Employee blocks out the time on their personal Outlook calendar
    c.  Employee sets up their out of office email reply for the time off, including: 1) when they will return; 2) who to reach out to with anything time sensitive
    d.  Employee plans for work coverage while they are out, in coordination with their supervisor
    e.  If the employee will be out of office for 6+ days, send a heads-up emails to the PRIDE team at least 5 business days in advance
    f.  Employee documents on their timecard *prior* to their time off
    g.  When the employee returns from time off: 1) Turn off out of office email reply, 2) Ensure their timecard accurately reflected their time off

[Sick Time Without Advance Notice]{.underline}

1.  Employee notifies their supervisor through email, call, or text before their work day starts and as soon as they can
2.  Employee determines with their supervisor who will add this to the PRIDE team calendar
3.  If possible, employee sets up their out of office email reply, including who to reach out to with anything time sensitive
4.  When the employee returns: 1) Turn off out of office email reply, 2) Document on: a) Asana (retroactively), b) timecard