# Publications and Conferences

## Authorship

We aim to discuss authorship early in the research process and have continuing conversations regarding team member roles. Plans can change and contributions may evolve over time. If you have authorship questions during the process of working on a project, we want you to feel empowered to ask these questions. There are many possible guidelines for determining authorship. PRIDE recommends [ICMJE recommendations](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) guidelines as one possible for determining who gets authorship and in what order:

-   Substantial contributions to conception or design *OR* data acquisition, analysis, or interpretation
-   *AND* drafting the article or revising it critically for important intellectual content
-   *AND* final approval and agreement to be accountable for the work

Beyond ICMJE, PRIDE suggests using Contributor Role Taxonomy ([CRediT](https://credit.niso.org/)) as an option for outlining the responsibilities of each author. It is recommended that CRediT statements are included in the acknowledgements of manuscripts to report each author’s contribution. This clarifies roles and is increasingly requested by journals.

For all papers or conference presentations using PRIDE data, it is expected that one of the co-Directors will serve as the last author. 

While not required, we encourage investigators using PRIDE data to include community partners as co-authors on manuscripts when appropriate. Our PRIDEnet community partners provide valuable feedback throughout the research process and often make substantial contributions to study design, interpretation, and dissemination that merit authorship recognition.

## Publications

Scientific writing is difficult! For anyone new to scientific writing (or those who have been writing for a long time), PRIDE recommends referring to reporting guidelines published as part of the [EQUATOR network](http://www.equator-network.org/) (Enhancing the QUAlity and Transparency Of health Research)—an international initiative that seeks to improve the reliability and value of published health research literature. Reporting guidelines promote clear reporting of methods and results to allow critical appraisal of the manuscript. The EQUATOR network has several reporting guidelines for different types of study design, and for many biomedical and health journals, these guidelines are sometimes asked to be submitted as supplemental files by journals along with the main manuscript.

Given the study design of The PRIDE Study, the 2 most common reporting guidelines are:

-   Strengthening the reporting of observational studies in epidemiology ([STROBE](https://www.equator-network.org/reporting-guidelines/strobe/))
-   Consolidated criteria for reporting qualitative research ([COREQ](https://www.equator-network.org/reporting-guidelines/coreq/))

All manuscripts using data from The PRIDE Study are required to be reviewed by The PRIDE Study prior to submission for publication. This is a necessary step to confirm that the submissions are aligned with The PRIDE Study's mission and match the approved Ancillary Study application. Collaborators (internal or external to PRIDE) should submit their complete manuscript and all associated files for review through our online [submission form](https://airtable.com/appr3ByWPVLLqok8I/pagUv4U3WrhkHAcBA/form).

PRIDE requires at least 2 weeks to review manuscripts prior to initial journal submission and at least 1 week to review revisions requested by journals (revise and resubmit). While we recognize that extenuating circumstances may occasionally necessitate expedited review, collaborators are expected to plan proactively to ensure sufficient time for the PRIDE team to provide feedback and for collaborators to incorporate that feedback before submission deadlines.

Once the paper has been submitted, please notify our [research team](mailto:review@pridestudy.org), addressing your email to our PRIDEnet Clinical Research Coordinator Associate, Ell Hundertmark, so that we can keep track of all paper submissions.

### Acknowledgements

It is important to acknowledge the contributions of PRIDE participants in sharing their data with The PRIDE Study, collaborators who may have supported the research but not to the point that would merit authorship, and grant funding supported the research. We provide several boilerplate language below that can be adapted as needed for all paper submissions.

> **Acknowledgement.** The PRIDE Study is a community-engaged research project that serves and is made possible by LGBTQIA+ community involvement at multiple points in the research process, including the dissemination of findings. We acknowledge the courage and dedication of The PRIDE Study participants for sharing their stories; the careful attention of PRIDEnet Participant Advisory Committee (PAC) members for reviewing and improving every study application; and the enthusiastic engagement of PRIDEnet Ambassadors and Community Partners for bringing thoughtful perspectives as well as promoting enrollment and disseminating findings. For more information, please visit https://pridestudy.org/pridenet. In acknowledgment of time spent and expertise provided reviewing research, PAC members are provided a stipend for their time.
>
> **Funding.** This study was partially funded by the Patient-Centered Outcomes Research Institute (PPRN-1501–26848 to MRL) and the National Institute on Drug Abuse of the National Institutes of Health (K24DA057874 to AF). The statements in this manuscript are solely the responsibility of the authors and do not necessarily represent the views of PCORI, its Board of Governors, or its Methodology Committee and the National Institutes of Health.
>
> **Conflict of Interests Disclosure.** Dr. Obedin-Maliver has received consultation fees from Ibis Reproductive Health, Hims and Hers Health Inc., Folx Health Inc., Sage Therapeutics and Upstream Inc. on topics unrelated to this work. Dr. Lunn received consultation fees from Hims and Hers Health Inc., Folx Health Inc., Otsuka Pharmaceutical Development and Commercialization Inc., and the American Dental Association on topics unrelated to this work. Dr. Tran received consultation fees from the *All of Us* Research Program Resources Access Board. No other disclosures were reported.

### Code and Data Sharing {#sec-code-data-share}

**Code Sharing.** While not required, we encourage investigators to consider sharing the code associated with their study. This is one approach to open science that we believe can improve the rigor and reproducibility of our research. There are several ways to share code:

-   Supplemental text or PDF file as part of submission
-   Through PRIDE GitHub and Zenodo accounts
-   Open Science Framework

Code sharing is increasingly requested by journals; however, the process can vary. The simplest approach may be to provide the code in text or PDF form as part of the supplemental materials with outputs and any identifying information excluded. However, if investigators wish to make their code publicly available and not restricted by journal access, our recommendation is to deposit the code in PRIDE's GitHub as a repository and link it to our Zenodo account. There are several advantages to this approach:

-   GitHub allows for clear documentation of what was done in the analysis including all dependencies, versions, and computational environment
-   Zenodo assigns a Digital Object Identifier to the code that provides a permanent web address that can be referenced
-   Identifying information (author names, institutions, etc) can be masked for double-blind review
-   Version tracking that can allow identifying information to be unblinded after paper acceptance while preserving connection to previous versions

For investigators who are relying on our team to conduct analyses internally and are interested in code sharing through PRIDE’s GitHub and Zenodo accounts, we recommend reaching to our biostatistician, Nguyen Tran, who can add the code to GitHub and Zenedo. Once this has been completed, we will provide investigators with a web address and a Digital Object Identifier to a permanent, de-identified snapshot of the code that can be referenced the in paper.

**Data Sharing.** It is the position of The PRIDE Study to not publicly share datasets generated and/or analyzed for any study due to ethical restrictions related to sensitive participant information. Any investigators interested in conducting research using data from The PRIDE Study are welcome to submit a proposal through our [Ancillary Study process](https://pridestudy.org/collaborate) (see @sec-anc-study for more details). We have boilerplate language that can be used as part of the data sharing statement for all paper submissions.

> **Data Availability Statement.** The datasets generated and/or analyzed during the current study are not publicly available due to ethical restrictions related to sensitive participant information but are available from the corresponding author on reasonable request. Researchers interested in The PRIDE Study data may submit a brief application which is reviewed by both a Research Advisory Committee (composed of scientists) and Participant Advisory Committee (composed of participants) to affirm appropriate data use. Details about the Ancillary Study process are available at www.pridestudy.org/collaborate or by contacting support\@pridestudy.org or 855-421-9991 (toll-free).

One possible alternative to data sharing of PRIDE Study data is to generate a synthetic dataset with similar characteristics to the original data.<sup>[1](#sec-repo-resources)</sup>  This can be done using `worcs::synthetic()` which defaults to a random forest algorithm to generate synthetic data; other models can be specified to generate synthetic values.

``` r
iris_syn <- worcs::synthetic(iris)
```

### Preprints

While not required, preprints are one possible option for investigators who are interested in getting their work out sooner. It is important to note that preprints are not peer-reviewed and are potentially subjected to change after going through the journal review process. The general advantage for posting on preprint servers is that these papers will be free for public access, which may be relevant if study findings have time-sensitive policy-related implications, and can be listed on resumes, biosketches, or curriculum vitae for grant applications, job opportunities, or promotion. Commonly used preprint serves include arXiv, medRxiv, PysArXiv, OSF, and Zenodo. Stanford faculty, students, and affiliates may also post preprints in the [Stanford Digital Repository](https://sdr.library.stanford.edu/).

### Research Dissemination Back to LGBTQIA+ Communities

In order to “close the loop” and return value to participants that have contributed their data to The PRIDE Study, we require that all investigators who publish their studies using The PRIDE Study data to complete a community-friendly summary of research findings as part of our [dissemination guidelines](https://www.dropbox.com/scl/fi/qknjgc18fqgp7vgxc8q7z/The-PRIDE-Study-Research-Dissemination-Plan_2019-12-06.pdf?rlkey=p4nepjqxn7eu5xoup7x4e2hkc&e=1&dl=0). This requirement reflects our commitment to community-based participatory research and ensures that LGBTQIA+ participants directly benefit from their involvement in the study. The community-friendly summary should be written in accessible, non-technical language that avoids jargon and clearly explains what the research found, why it matters, and how it might impact LGBTQIA+ health and wellbeing. This process is as follows:

1.  **Notify The PRIDE Study Team.** Upon acceptance of the manuscript, contact our our [research team](mailto:review@pridestudy.org) and indicate our Program Management Director, Daniel Moretti, and our PRIDEnet Clinical Research Coordinator Associate, Ell Hundertmark, as the contact people, to notify us of the acceptance and initiate the research dissemination process.
2.  **Complete Community-Friendly Summary.** The PRIDE Study team will send a template of the community-friendly summary to the first author for completion within 1 week. Along with the summary, we will request addition information including whether the paper will be open-access, NIH funding support details, anticipated publication date, and final article PDF and citation.  
3.  **Collaborative Review and Editing**. Our team will review the summary and provide edits as needed to ensure that the language is accessible to participants.
4.  **Dissemination.** Once the paper is published, the community-friendly summary will be shared with participants through our email listserv and posted on our website. Examples of previous summaries can be found on our [website](https://pridestudy.org/research).

## Conferences {#sec-conferences}

Any abstract submissions to conferences that use data from The PRIDE Study are required to be reviewed by The PRIDE Study prior to submission. The PRIDE Study requests at least 1 week in order to provide feedback. First authors of all abstracts should share their abstracts to all co-authors *via* email while copying [research team](mailto:review@pridestudy.org).

For trainees that are under the direct mentorship of one of The PRIDE Study co-directors, it is recommended that they reach out to their mentor with ample time in order to discuss funding options for the trip. 

## Resources {#sec-repo-resources}

-   Van Lissa CJ, Brandmaier AM, Brinkman L, et al. WORCS: A workflow for open reproducible code in science. *Data Science*. 2021;4(1):29-49. doi:[10.3233/DS-210031](https://doi.org/10.3233/DS-210031)

-   Nowok, B., Raab, G.M and Dibben, C. synthpop: Bespoke creation of synthetic data in R. *Journal of Statistical Software*. 2016:74(11):1-26. [doi:10.18637/jss.v074.i11](https://doi.org/10.18637/jss.v074.i11) .