# LGBTQIA+ Specific Analytic Considerations

LGBTQIA+ identities are multidimensional. This is reflected in how we collect information on different dimensions of sex, gender, and sexuality in The PRIDE Study and the ways in which we analyze these data in our statistical approach. This is grounded in both the methodological literature and the lived experiences of LGBTQIA+ community members of PRIDEnet.

## Measures of Gender, Sex, and Sexuality

The PRIDE Study collects several measures may be particularly relevant for LGBTQIA+ health research, depending on the specific research question:

+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| Variable           | Description                                                                                        | Availability                               |
+====================+====================================================================================================+============================================+
| `GENDERID_*`       | -   Selection of one (or multiple) options that describes current gender identity.                 | -   All annual questionnaires              |
|                    | -   Each gender identity is represented in a separate column.                                      | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `SELFBIN_GI`       | -   Selection of single option that best describe current gender identity.                         | -   All annual questionnaires              |
|                    |                                                                                                    | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `SAAB`             | -   Sex assigned at birth, for example on original birth certificate.                              | -   All annual questionnaires              |
|                    |                                                                                                    | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `INTERSEX`         | -   Self-identification as intersex.                                                               | -   All annual questionnaires              |
|                    |                                                                                                    | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `SAAB_INTERSEX`    | -   Sex assigned a birth, for example on original birth certificate, indicate intersex.            | -   2023-2025 annual questionnaires        |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `ORGANS_BORN_*`    | -   Selection of one (or multiple) options indicating the organs present at birth.                 | -   2018-2025 annual questionnaires        |
|                    | -   Each response is represented in a separate column.                                             | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `ORGANS_NOW_*`     | -   Selection of one (or multiple) options indicating the organs currently present.                | -   2018-2025 annual questionnaires        |
|                    | -   Each response is represented in a separate column.                                             | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `ORIENTATION_*`    | -   Selection of one (or multiple) options that describes current sexual orientation.              | -   All annual questionnaires              |
|                    | -   Each sexual orientation is represented in a separate column.                                   | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `SELFBIN_SO`       | -   Selection of single option that best describe current sexual orientation.                      | -   All annual questionnaires              |
|                    |                                                                                                    | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `ATTRACTION_ROM_*` | -   Selection of one (or multiple) options that describes current romantic feelings toward others. | -   2019-2025 annual questionnaire         |
|                    | -   Each romantic attraction is represented in a separate column.                                  | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+
| `ATTRACTION_SEX_*` | -   Selection of one (or multiple) options that describes current sexual attraction toward others. | -   2019-2025 annual questionnaire         |
|                    | -   Each sexual attraction is represented in a separate column.                                    | -   Lifetime health and experiences survey |
+--------------------+----------------------------------------------------------------------------------------------------+--------------------------------------------+

## Recommended Analytic Strategy 

While no single approach fits all research questions, we offer a few key considerations to guide your analytic decisions when working with The PRIDE Study data.

Our approach to including measures of gender, sex, and sexuality balances two essential priorities: representing the diverse identities of PRIDE Study participants while capturing the constructs most relevant to specific research questions. We achieve this balance through a two-part strategy.

### Descriptive Analysis

In reporting participant characteristics, we present the full diversity of identities held by participants, honoring the spectrum of gender identities and sexual orientations represented in the LGBTQIA+ community. Oftentimes, this includes reporting all possible responses for current gender identity and current sexual orientation.

### Theory-driven Operationalization

For specific research questions, we operationalize measures of gender, sex, and sexuality based on which construct is most relevant to the health outcome being studied. This requires engaging with the existing literature to understand whether gender identity, gender modality, intersex identity, sex assigned at birth, organ-specific status, hormonal status, sexual behavior, sexual orientation identity, enacted gender/sexual orientation stigma or discrimination, or some combination of these factors is most meaningful for the analysis at hand. Oftentimes a multistep approach, such as the validated two-step approach first outlined by Tate et al. (2013)<sup>[1](#sec-resources)</sup> for identifying cisgender and transgender people, is needed to accurately identify population of interest or analytic construct of interest.

## Resources {#sec-resources}

-   Bauer GR, Braimoh J, Scheim AI, Dharma C. Transgender-inclusive measures of sex/gender for population surveys: Mixed-methods evaluation and recommendations. *PLoS One*. 2017 May 25;12(5):e0178043. doi: [10.1371/journal.pone.0178043](https://doi.org/10.1371/journal.pone.0178043).
-   Bauer GR. Sex and Gender Multidimensionality in Epidemiologic Research. *Am J Epidemiol*. 2023 Jan 6;192(1):122-132. doi: [10.1093/aje/kwac173](https://doi.org/10.1093/aje/kwac173).
-   Restar AJ, Lett E, Menezes NP, Molino AR, Poteat TC, Dean LT, Glick JL, Baker KE, Cole SW. Getting precise about gender and sex measurement: a primer for epidemiologists. *Am J Epidemiol*. 2024 Dec 2;193(12):1861-1867. doi: [10.1093/aje/kwae144](https://doi.org/10.1093/aje/kwae144).
-   Suen LW, Lunn MR, Katuzny K, Finn S, Duncan L, Sevelius J, Flentje A, Capriotti MR, Lubensky ME, Hunt C, Weber S, Bibbins-Domingo K, Obedin-Maliver J. What Sexual and Gender Minority People Want Researchers to Know About Sexual Orientation and Gender Identity Questions: A Qualitative Study. *Arch Sex Behav*. 2020 Oct;49(7):2301-2318. doi: [10.1007/s10508-020-01810-y](https://doi.org/10.1007/s10508-020-01810-y).
-   Tate CC, Ledbetter JN, Youssef CP. A two-question method for assessing gender categories in the social and medical sciences. *J Sex Res*. 2013;50(8):767-76. doi: [10.1080/00224499.2012.690110](https://doi.org/10.1080/00224499.2012.690110).
-   Tordoff DM, Minalga B, Catháin NÓ, Fernandez A, Gross B, Glick SN; The Seattle Trans and Nonbinary Sexual Health (STARS) Advisory Board. Comparing two-step approaches to measuring gender identity: the reliability and applications of asking about sex assigned at birth vs transgender self-identification. *Am J Epidemiol*. 2025 May 7;194(5):1255-1263. doi: [10.1093/aje/kwae341](https://doi.org/10.1093/aje/kwae341).