# Contact

We are a small but mighty team dedicated to supporting investigators using The PRIDE Study data! We strive to provide responsive assistance throughout your research journey, from initial data requests to manuscript preparation and community dissemination. Please don't hesitate to reach out with questions—we're here to help ensure your research is successful and benefits the LGBTQIA+ communities we serve. Below are key team members and their areas of expertise to help direct your inquiries:

If you are a new investigator and interested in collaborating with The PRIDE Study, please reach us at: [support\@pridestudy.org](mailto:support@pridestudy.org). For specific inquiries, please review the information below for the relevant contact and their contact information.

| Name | Title | Email Address |
|------------------|------------------|-------------------------------------|
| Annesa Flentje, PhD | Co-Director | [aflentje\@stanford.edu](aflentje@stanford.edu) |
| Mitchell R. Lunn, MD, MAS | Co-Director | [lunn\@stanford.edu](lunn@stanford.edu) |
| Juno Obedin-Maliver, MD, MPH, MAS | Co-Director | [junoom\@stanford.edu](junoom@stanford.edu) |

: Requires specific information about The PRIDE Study, Ancillary Study Inquiry, Trainees under direct supervision, Grant application 

| Name | Title | Email Address |
|------------------|------------------|-------------------------------------|
| Daniel Moretti, MSc | Program Management Director | [dmoretti\@stanford.edu](dmoretti@stanford.edu) |
| Ell Hundertmark | PRIDEnet Clinical Research Coordinator Associate | [ellhun\@stanford.edu](ellhun@stanford.edu) |

: Community and participant engagement, PRIDEnet, Publications 

| Name | Title | Email Address |
|------------------|------------------|-------------------------------------|
| Nguyen K. Tran, PhD, MPH | Biostatistician | [nktran\@stanford.edu](nktran@stanford.edu) |

: Analytical support of approved or ongoing ancillary studies 